// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectHealthAPI.Data;

#nullable disable

namespace ProjectHealthAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323203605_AgregandoFechaPagos")]
    partial class AgregandoFechaPagos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectHealthAPI.Models.Alquiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoServicio")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraEntrada")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraSalida")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Alquileres");
                });

            modelBuilder.Entity("ProjectHealthAPI.Models.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoServicio")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraEntrada")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraSalida")
                        .HasColumnType("time without time zone");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("ProjectHealthAPI.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoCivil")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoCliente")
                        .HasColumnType("integer");

                    b.Property<int>("Genero")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ocupacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ProjectHealthAPI.Models.HistoriaMedica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ansioliticos")
                        .HasColumnType("boolean");

                    b.Property<bool>("Antidepresivos")
                        .HasColumnType("boolean");

                    b.Property<int>("ConsumoAlcohol")
                        .HasColumnType("integer");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dosificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EdadInicio")
                        .HasColumnType("integer");

                    b.Property<int>("Ejercicio")
                        .HasColumnType("integer");

                    b.Property<int>("EscalaDolor")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoCliente")
                        .HasColumnType("integer");

                    b.Property<string>("Farmaco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Fumador")
                        .HasColumnType("integer");

                    b.Property<string>("HobbiesDeportes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Traumatismos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("antecedentesPersonales")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("HistoriasMedicas");
                });

            modelBuilder.Entity("ProjectHealthAPI.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoCivil")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoCliente")
                        .HasColumnType("integer");

                    b.Property<int>("Genero")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ocupacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Peso")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("ProjectHealthAPI.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlquilerId")
                        .HasColumnType("integer");

                    b.Property<int?>("CitaId")
                        .HasColumnType("integer");

                    b.Property<string>("Comprobante")
                        .HasColumnType("text");

                    b.Property<int>("EstadoPago")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoPago")
                        .HasColumnType("integer");

                    b.Property<int>("TipoServicio")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlquilerId");

                    b.HasIndex("CitaId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("ProjectHealthAPI.Models.Alquiler", b =>
                {
                    b.HasOne("ProjectHealthAPI.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ProjectHealthAPI.Models.Cita", b =>
                {
                    b.HasOne("ProjectHealthAPI.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ProjectHealthAPI.Models.HistoriaMedica", b =>
                {
                    b.HasOne("ProjectHealthAPI.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ProjectHealthAPI.Models.Pago", b =>
                {
                    b.HasOne("ProjectHealthAPI.Models.Alquiler", "Alquiler")
                        .WithMany()
                        .HasForeignKey("AlquilerId");

                    b.HasOne("ProjectHealthAPI.Models.Cita", "Cita")
                        .WithMany()
                        .HasForeignKey("CitaId");

                    b.Navigation("Alquiler");

                    b.Navigation("Cita");
                });
#pragma warning restore 612, 618
        }
    }
}
